site_name: Documentation CertiSoft

theme:
  name: material
  language: fr
  logo: assets/certisoft-logo-white.png
  favicon: assets/favicon.ico

  palette:
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Mode sombre
      primary: custom

    - scheme: slate
      toggle:
        icon: octicons/sun-16
        name: Mode clair
      primary: custom

  features:
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

extra_css:
  - stylesheets/theme-colors.css

markdown_extensions:
  - attr_list

extra:
  homepage: https://certisoft.ch
  social:
    - icon: fontawesome/brands/github-alt
      link: https://boardmanagementsystems.ch

copyright: 2023 <a href="https://certisoft.ch" target="_blank">CertiSoft SA</a> &copy;